count:
	g++ counting_sort.cpp util.cpp -o counting_sort
	./counting_sort
	rm counting_sort
radix:
	g++ radix_sort.cpp util.cpp -o radix_sort
	./radix_sort
	rm radix_sort
bucket:
	g++ bucket_sort.cpp util.cpp -o bucket_sort
	./bucket_sort
	rm bucket_sort
